# Generated by Django 3.2.13 on 2022-11-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.CharField(max_length=6)),
                ('booktitle', models.CharField(max_length=50)),
                ('bookauthor', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
